server:
  port: 8888

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.52.160.81:3306/babybei?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&autoConnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-on-borrow: false
    test-while-idle: true
    max-conn-lifetime-millis: 3600000

  mail:
    host: smtp.yeah.net
    port: 994
    username: hutool@yeah.net
    password: q1w2e3
    protocol: smtp
    test-connection: true
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: xkcoding
  task:
    scheduling:
      pool:
        size: 20
      thread-name-prefix: Job-Thread-

  redis:
    host: 47.52.160.81
    port: 6379
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    # database: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    password: 123456

## 缓存
redis-cache:
  ttl: 1800 #30min

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
## 监控管理
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


###文件上传
upload:
  path: uploads

url:
  ignore:
    get:
      - "/api/auth/login"
    post:
      - "/auth/login"
      - "/auth/registry"
    pattern:
      - "/test/*"

##jwt
jwt:
  config:
    key: fadedfate
    ttl:   86400 #s, 1 day
    remember: 604800 #记住我，7天有效期;小于0为永远记住
    redis-key-prefix: jwt.
##日志
logging:
  file: logs/app.log
  level:
    com:
      zhumingbei:
        babybei_server: INFO
    org:
      springframework:
        web: INFO
        security: INFO
    root: WARN


