server:
  port: 8001

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.52.160.81:3306/vhr?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&autoConnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-on-borrow: false
    test-while-idle: true
    max-conn-lifetime-millis: 3600000

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径

